#!/bin/sh

ENV_PROP_FILE=/solution/$CONFIG/data/environment.properties
PROV_PROP_FILE=$JBOSS_USER_HOME/provisioning.properties

echo "Configuring Data Source values"
for val in os tp archive audit rs wf
do
echo "Replacing $val";
	valHost=`/opt/verify/parser.sh db.$val.host $ENV_PROP_FILE`
	valPort=`/opt/verify/parser.sh db.$val.port $ENV_PROP_FILE`
	valName=`/opt/verify/parser.sh db.$val.name $ENV_PROP_FILE`
	valUser=`/opt/verify/parser.sh db.$val.user $ENV_PROP_FILE`
	valPassword=`/opt/verify/parser.sh db.$val.password.encoded $ENV_PROP_FILE`
	isProv=`/opt/verify/parser.sh ime.with.prov $ENV_PROP_FILE`
	sed -i "s/@db.$val.host@/$valHost/g" "${JBOSS_HOME}/standalone/configuration/caim-standalone-config.xml"
	sed -i "s/@db.$val.port@/$valPort/g" "${JBOSS_HOME}/standalone/configuration/caim-standalone-config.xml"
	sed -i "s/@db.$val.name@/$valName/g" "${JBOSS_HOME}/standalone/configuration/caim-standalone-config.xml"
	sed -i "s/@db.$val.user@/$valUser/g" "${JBOSS_HOME}/standalone/configuration/caim-standalone-config.xml"
	sed -i "s/@db.$val.password.encoded@/$valPassword/g" "${JBOSS_HOME}/standalone/configuration/caim-standalone-config.xml"
	echo "Replacement done for $val";
done
echo "Configuration of Data source is done";

echo "Configuring the SMTP properties";
	smtpHost=`/opt/verify/parser.sh mail.smtp.host $ENV_PROP_FILE`
	smtpPort=`/opt/verify/parser.sh mail.smtp.port $ENV_PROP_FILE`
	sed -i "s/@mail.smtp.host@/$smtpHost/g" "${JBOSS_HOME}/standalone/configuration/caim-standalone-config.xml"
	sed -i "s/@mail.smtp.port@/$smtpPort/g" "${JBOSS_HOME}/standalone/configuration/caim-standalone-config.xml"
echo "Configuration of SMTP properties is done";
sed -i "s/workpoint.stored.procedure = true/workpoint.stored.procedure = false/g"  ${JBOSS_HOME}/standalone/deployments/iam_im.ear/config/workpoint-server.properties

isEnv=`/opt/verify/parser.sh sample.env.creation $ENV_PROP_FILE`

if [ "$isEnv" == "YES" ]; then

        provDirHost=`/opt/verify/parser.sh ca.prov.dir.hostname $ENV_PROP_FILE`

        provDirPort=`/opt/verify/parser.sh ca.prov.dir.port $ENV_PROP_FILE`

        provDirUser=`/opt/verify/parser.sh ca.prov.dir.username $ENV_PROP_FILE`
		
		ldapDirHost=`/opt/verify/parser.sh ca.dir.hostname $ENV_PROP_FILE`

        ldapDirPort=`/opt/verify/parser.sh ca.dir.port $ENV_PROP_FILE`

        fwHost=`/opt/verify/parser.sh iam.framework.basehost $ENV_PROP_FILE`

        IM_PS_PASSWORD=`/opt/verify/parser.sh IM_PS_PASSWORD $PROV_PROP_FILE`
		
		sample_env=`/opt/verify/parser.sh sample.env $ENV_PROP_FILE`
		echo "sample_env is  $sample_env"
		
        #im_ps_passwd="$(openssl base64 -d <<< $IM_PS_PASSWORD)"
		im_ps_passwd="$(java -cp /opt/utils/base64util.jar:/opt/utils/cacommons.jar DecodeBase64AsUTF8 $IM_PS_PASSWORD)"
	echo "Default IME YES";
	cp -f /solution/$CONFIG/ime/$sample_env/* ${JBOSS_HOME}/standalone/deployments/iam_im.ear/user_console.war/META-INF/
	if [ "$isProv" == "true" ]; then
		############# Modifying prov dir props #####################
		echo "IME with Provisioning YES";
        	sed -i "s/@ProvSMDirHost@/$provDirHost/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
        	sed -i "s/@ProvSMDirPort@/$provDirPort/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
        	sed -i "s/@ProvSMDirUser@/$provDirUser/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
        	sed -i "s/@ProvSMDirPassword@/$im_ps_passwd/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
        	sed -i "s/@baseurl@/$fwHost/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
        	sed -i "s/@SMDirHost@/$ldapDirHost/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
        	sed -i "s/@SMDirPort@/$ldapDirPort/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"

      else
			############# Modifying ldap dir props #####################
		mv $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment_WithoutProv.properties $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties
		mv $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/EnvironmentSettings_WithoutProv.xml $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/EnvironmentSettings.xml
		sed -i "s/@baseurl@/$fwHost/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
		sed -i "s/@SMDirHost@/$ldapDirHost/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
		sed -i "s/@SMDirPort@/$ldapDirPort/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties"
     fi
			
else
     mv $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment.properties $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/user_console.war/META-INF/SampleEnvironment_backup.properties
fi
