#!/bin/sh

ENV_PROP_FILE=/solution/$CONFIG/data/environment.properties
PROV_PROP_FILE=$JBOSS_USER_HOME/provisioning.properties

im_version=$(grep -Po "(?<=^im_version=).*" $ENV_PROP_FILE)

im_latest_bld_no=$(grep -Po "(?<=^im_latest_bld_no=).*" $ENV_PROP_FILE)

IM_PS_PASSWORD_PBES=$(grep -Po "(?<=^IM_PS_PASSWORD_PBES=).*" $PROV_PROP_FILE)

IM_PS_PASSWORD=$(grep -Po "(?<=^IM_PS_PASSWORD=).*" $PROV_PROP_FILE)

REPOSITORY_USERNAME=$(grep -Po "(?<=^REPOSITORY_USERNAME=).*" $PROV_PROP_FILE)

REPOSITORY_PASSWORD=$(grep -Po "(?<=^REPOSITORY_PASSWORD=).*" $PROV_PROP_FILE)

wp_username=$(grep -Po "(?<=^remote.connection.default.username=).*" $ENV_PROP_FILE)

wp_password=$(grep -Po "(?<=^remote.connection.default.password=).*" $ENV_PROP_FILE)

wp_host=$(grep -Po "(?<=^remote.connection.default.host=).*" $ENV_PROP_FILE)

MIN_HEAP=$(grep -Po "(?<=^MIN_HEAP=).*" $ENV_PROP_FILE)

MAX_HEAP=$(grep -Po "(?<=^MAX_HEAP=).*" $ENV_PROP_FILE)

MaxPermSize=$(grep -Po "(?<=^MaxPermSize=).*" $ENV_PROP_FILE)



cd -
#LATEST_BUILD_NO_URL='http://im-bld-arc.ca.com/showbuild.php?product=imdvd12-6-06-Nipuna&latest_build_number'
#latest_bld_no="$(wget $LATEST_BUILD_NO_URL -q -O -)"
version=$im_version
version="$version."
version="$version$im_latest_bld_no"
echo "$version"

#im_ps_passwd="$(openssl base64 -d <<< $IM_PS_PASSWORD)"
im_ps_passwd="$(java -cp /opt/utils/base64util.jar:/opt/utils/cacommons.jar DecodeBase64AsUTF8 $IM_PS_PASSWORD)"

#im_ps_admin_passwd="$(openssl base64 -d <<< $REPOSITORY_PASSWORD)"
im_ps_admin_passwd="$(java -cp /opt/utils/base64util.jar:/opt/utils/cacommons.jar DecodeBase64AsUTF8 $REPOSITORY_PASSWORD)"

touch $JBOSS_STANDALONE_DIR/configuration/mgmt-groups.properties

#################### JBOSS HEAP SIZE ##########################
sed -i "s/Xms64m/Xms$MIN_HEAP/g" "$JBOSS_HOME/bin/standalone.conf"
sed -i "s/Xmx512m/Xmx$MAX_HEAP/g" "$JBOSS_HOME/bin/standalone.conf"
sed -i "s/MaxPermSize=256m/MaxPermSize=$MaxPermSize/g" "$JBOSS_HOME/bin/standalone.conf"


echo 'JAVA_OPTS="$JAVA_OPTS -Dcom.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager=true"' >> $JBOSS_HOME/bin/standalone.conf
if [ "$JBOSS_VERSION" = "wildfly" ]
    then
        if [  -f $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/META-INF/jboss-deployment-structure.xml.jboss8 ]; then
            mv $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/META-INF/jboss-deployment-structure.xml.jboss8 $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/META-INF/jboss-deployment-structure.xml
    fi
fi

sed -i "s|%etacallbacksharedsecret%|$IM_PS_PASSWORD_PBES|g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/custom/identitymanager/systemWideProperties.properties"
sed -i "s/^version_string=.*/version_string=$version/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/config/com/netegrity/config/product_versioninfo.properties"

############ Add user in jboss ############################
############## This is for Work point desingner ##############
sh $JBOSS_HOME/bin/add-user.sh -a -s -u $wp_username -p $wp_password
