#!/bin/sh

ENV_PROP_FILE=/solution/$CONFIG/data/environment.properties
PROV_PROP_FILE=$JBOSS_USER_HOME/provisioning.properties

im_version=`/opt/verify/parser.sh im_version $ENV_PROP_FILE`
im_latest_bld_no=`/opt/verify/parser.sh im_latest_bld_no $ENV_PROP_FILE`
IM_PS_PASSWORD_PBES=`/opt/verify/parser.sh IM_PS_PASSWORD_PBES $PROV_PROP_FILE`
IM_PS_PASSWORD=`/opt/verify/parser.sh IM_PS_PASSWORD $PROV_PROP_FILE`
REPOSITORY_USERNAME=`/opt/verify/parser.sh REPOSITORY_USERNAME $PROV_PROP_FILE`
REPOSITORY_PASSWORD=`/opt/verify/parser.sh REPOSITORY_PASSWORD $PROV_PROP_FILE`
wp_username=`/opt/verify/parser.sh remote.connection.default.username $ENV_PROP_FILE`
wp_password=`/opt/verify/parser.sh remote.connection.default.password $ENV_PROP_FILE`
wp_host=`/opt/verify/parser.sh remote.connection.default.host $ENV_PROP_FILE`


MIN_HEAP=`/opt/verify/parser.sh MIN_HEAP $ENV_PROP_FILE`
MAX_HEAP=`/opt/verify/parser.sh MAX_HEAP $ENV_PROP_FILE`
MaxPermSize=`/opt/verify/parser.sh MaxPermSize $ENV_PROP_FILE`


cd -
#LATEST_BUILD_NO_URL='http://im-bld-arc.ca.com/showbuild.php?product=imdvd12-6-06-Nipuna&latest_build_number'
#latest_bld_no="$(wget $LATEST_BUILD_NO_URL -q -O -)"
version=$im_version
version="$version."
version="$version$im_latest_bld_no"
echo "$version"

#im_ps_passwd="$(openssl base64 -d <<< $IM_PS_PASSWORD)"
im_ps_passwd="$(java -cp /opt/utils/base64util.jar:/opt/utils/cacommons.jar DecodeBase64AsUTF8 $IM_PS_PASSWORD)"

#im_ps_admin_passwd="$(openssl base64 -d <<< $REPOSITORY_PASSWORD)"
im_ps_admin_passwd="$(java -cp /opt/utils/base64util.jar:/opt/utils/cacommons.jar DecodeBase64AsUTF8 $REPOSITORY_PASSWORD)"

touch $JBOSS_STANDALONE_DIR/configuration/mgmt-groups.properties

#################### JBOSS HEAP SIZE ##########################
sed -i "s/Xms64m/Xms$MIN_HEAP/g" "$JBOSS_HOME/bin/standalone.conf"
sed -i "s/Xmx512m/Xmx$MAX_HEAP/g" "$JBOSS_HOME/bin/standalone.conf"
sed -i "s/MaxPermSize=256m/MaxPermSize=$MaxPermSize/g" "$JBOSS_HOME/bin/standalone.conf"


echo 'JAVA_OPTS="$JAVA_OPTS -Dcom.sun.jersey.server.impl.cdi.lookupExtensionInBeanManager=true"' >> $JBOSS_HOME/bin/standalone.conf
if [ "$JBOSS_VERSION" = "wildfly" ]
    then
        if [  -f $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/META-INF/jboss-deployment-structure.xml.jboss8 ]; then
            mv $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/META-INF/jboss-deployment-structure.xml.jboss8 $JBOSS_STANDALONE_DIR/deployments/iam_im.ear/META-INF/jboss-deployment-structure.xml
    fi
fi

sed -i "s|%etacallbacksharedsecret%|$IM_PS_PASSWORD_PBES|g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/custom/identitymanager/systemWideProperties.properties"
sed -i "s/^version_string=.*/version_string=$version/g" "$JBOSS_STANDALONE_DIR/deployments/iam_im.ear/config/com/netegrity/config/product_versioninfo.properties"

############ Add user in jboss ############################
############## This is for Work point desingner ##############
sh $JBOSS_HOME/bin/add-user.sh -a -s -u $wp_username -p $wp_password
