#!/bin/sh
# * ----------------------------------------------------------------------
# *               Proprietary and Confidential Information
# *
# * This material contains, and is part of a computer software program
# * which is, proprietary and confidential information owned by CA INC.
# * The program, including this material, may not be duplicated, disclosed 
# * or reproduced in whole or in part for any purpose without the express 
# * written authorization of CA. All authorized reproductions must be marked
# * with this legend.
# *
# *                          Copyright (c) 2015
# *                                  CA
# *                          All rights reserved
# *
# * ----------------------------------------------------------------------
# *
# * # * Identity Manager - ForardInc Demo - MySQL Configuration File Init
# *
# * ----------------------------------------------------------------------

# Copying the my.cnf file and changing the permission
echo "Copying of the my.cnf to /etc/mysql folder ...."
/bin/cp -f /solution/$CONFIG/data/my.cnf  /etc/mysql/my.cnf
/bin/chmod 644 /etc/mysql/my.cnf
